name: sample_project
description: Example project for ICM and ICS
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^10.0.0
  mocktail: ^1.0.0

  inqvine_core_simulate:
    path: ../packages/inqvine_core_simulate

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true