name: inqvine_core_simulate
description: Build mock UIs and action mocks from within a simulator
version: 1.3.0
homepage: https://github.com/inqvine-llc

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^3.0.7
  mocktail: ^0.3.0
  device_preview: ^1.0.0
  inqvine_core_main: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0

flutter: