name: inqvine_core_simulate
description: Build mock UIs and action mocks from within a simulator
version: 2.0.1
homepage: https://github.com/inqvine-llc

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^10.0.0
  mocktail: ^1.0.0
  device_preview: ^1.1.0
  inqvine_core_main: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  import_sorter: ^4.6.0

flutter: