name: inqvine_core_main
description: Useful functionality, widgets, and more shared between all Inqvine products
version: 1.0.0
author: Inqvine

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  hooks_riverpod: ^0.13.0
  get_it: ^6.0.0
  event_bus: ^2.0.0

  # Data Classes
  protobuf: ^2.0.0

  # Tooling
  jiffy: ^4.0.0
  crypto: ^3.0.0
  device_info_plus: ^1.0.0

  # Debugging
  logger: ^1.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.0
  build_runner: ^1.11.5

flutter:
