name: inqvine_core_main
description: Useful functionality, widgets, and more shared between all Inqvine products
version: 2.0.2
homepage: https://github.com/inqvine-llc

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  hooks_riverpod: ^2.3.7
  flutter_hooks: ^0.20.0
  flutter_riverpod: ^2.3.6
  riverpod: ^2.3.6
  get_it: ^7.2.0
  event_bus: ^2.0.0

  # Data Classes
  protobuf: ^3.1.0
  fixnum: ^1.0.0

  # Tooling
  jiffy: ^6.2.1
  crypto: ^3.0.1
  universal_io: ^2.0.4

  # Debugging
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.17
  build_runner: ^2.1.7
  import_sorter: ^4.6.0

flutter:
