name: inqvine_core_main
description: Useful functionality, widgets, and more shared between all Inqvine products
version: 1.0.1
homepage: https://github.com/inqvine-llc

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.6"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  async: ^2.6.0
  riverpod: ^0.14.0+3
  flutter_riverpod: ^0.14.0+3
  hooks_riverpod: ^0.14.0+4
  flutter_hooks: ^0.17.0
  get_it: ^7.2.0
  event_bus: ^2.0.0

  # Data Classes
  protobuf: ^2.0.0
  fixnum: ^1.0.0

  # Tooling
  jiffy: ^4.1.0
  crypto: ^3.0.1
  universal_io: ^2.0.4

  # Debugging
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.15
  build_runner: ^2.1.1

flutter:
