name: inqvine_core_main
description: Useful functionality, widgets, and more shared between all Inqvine products
version: 1.1.2
homepage: https://github.com/inqvine-llc

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.6"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2
  flutter_riverpod: ^1.0.3
  riverpod: ^1.0.3
  get_it: ^7.2.0
  event_bus: ^2.0.0

  # Data Classes
  protobuf: ^2.0.1
  fixnum: ^1.0.0

  # Tooling
  jiffy: ^5.0.0
  crypto: ^3.0.1
  universal_io: ^2.0.4

  # Debugging
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.17
  build_runner: ^2.1.7

flutter:
