name: inqvine_starter_project
description: Example project for ICM and ICS
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^3.0.7
  mocktail: ^0.3.0

  inqvine_core_simulate:
    path: ../packages/inqvine_core_simulate

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true