name: inqvine_core_ui
description: Useful UI components for across applications
version: 0.0.12-nullsafety.0
homepage: https://github.com/inqvine-llc

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  inqvine_core_main: ^0.0.10-nullsafety.0

  # Data Classes
  protobuf: ^2.0.0
  fixnum: ^1.0.0

  # UI
  expandable: ^5.0.1
  animations: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
