name: inqvine_core_ui
description: Useful UI components for across applications
version: 2.1.2
homepage: https://github.com/inqvine-llc

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  inqvine_core_main: ^2.1.1

  # Data Classes
  protobuf: ^3.1.0
  fixnum: ^1.0.0

  # UI
  expandable: ^5.0.1
  animations: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: ^4.6.0

flutter:
