name: inqvine_core_firebase
description: Seemless integration with common Firebase components for Inqvine Core
version: 2.1.2
homepage: https://github.com/inqvine-llc

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  inqvine_core_main: ^2.1.1

  # Data Classes
  protobuf: ^3.1.0
  fixnum: ^1.0.0

  # Third Party
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: ^4.6.0