name: inqvine_core_firebase
description: Seemless integration with common Firebase components for Inqvine Core
version: 1.3.2
homepage: https://github.com/inqvine-llc

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.6"

dependencies:
  flutter:
    sdk: flutter

  inqvine_core_main: ^1.3.2

  # Data Classes
  protobuf: ^2.0.1
  fixnum: ^1.0.0

  # Third Party
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  cloud_firestore: ^3.1.12
  firebase_messaging: ^11.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  import_sorter: ^4.6.0