name: inqvine_core_firebase
description: Seemless integration with common Firebase components for Inqvine Core
version: 1.0.0
homepage: https://github.com/inqvine-llc

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  inqvine_core_main: ^1.0.0

  # Data Classes
  protobuf: ^2.0.0
  fixnum: ^1.0.0

  # Third Party
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  firebase_messaging: ^10.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter