name: inqvine_core_firebase
description: Seemless integration with common Firebase components for Inqvine Core
version: 0.0.4-nullsafety.0
homepage: https://github.com/inqvine-llc

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  inqvine_core_main: ^0.0.3-nullsafety.0

  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_crashlytics: ^1.0.0
  firebase_messaging: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter