on:
  pull_request_review:
    types: [submitted]
    branches: ['master','develop']

  pull_request:
    branches: ['master','develop']

name: Prepare and Build Packages
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: ./.github/workflows/scripts/install-flutter.sh dev
    - run: ./.github/workflows/scripts/install-tools.sh
    - run: 'melos bootstrap'
    - run: 'melos run test'
    - if: ${{ always() }}
      run: 'genhtml coverage/lcov.info -o coverage/html'
    - if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: inqvine-core-coverage
        path: coverage/