on:
  pull_request_review:
    types: [submitted]
    branches: ['master','develop']

  pull_request:
    branches: ['master','develop']

name: Prepare and Build Packages
jobs:
  core_test:
    name: Run Melos Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: 'sudo apt-get update -qq -y'
    - run: 'sudo apt-get install lcov -y'
    - run: 'flutter pub global activate melos'
    - run: 'melos run analyze'
    - run: 'melos run clean:flutter'
    - run: 'melos run build:runner'
    - run: 'melos run test'
    - if: ${{ always() }}
      run: 'genhtml coverage/lcov.info -o coverage/html'
    - if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: inqvine-core-coverage
        path: coverage/